services:
  - type: web
    name: tlb-rebranding-web
    runtime: python
    rootDir: webapp
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:flask_app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
